### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by jmsaulnier** [thinkingboxmedia/static-web-starter-kit#9]
- [x] Remove Precss (use PostCSS plugins instead)
- [x] Update to React-Router 4
- [x] Switch npm to Yarn 
- [ ] Update components generators 
- [ ] Add route generators
- [ ] Add components
   [ ] Preloader
   [ ] Sound
   [ ] YoutubeCustomPlayer
   [ ] Rotate
   [ ] Sharing (Twitter / Facebook)
- [x] Add async / await - spread operator examples
- [x] Add default props values
- [x] Add module-resolver babel plugin (and add "src" alias)
- [ ] Add PWA example (ex: Service workers, etc)
- [ ] Add tests example with Enzyme and Jest
- [ ] Add documentation (ex: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#updating-to-new-releases )
- [ ] Add HTTPS option in development
- [ ] Add storyboard ( https://github.com/kadirahq/react-storybook )
- [ ] Switch ESlint to Prettier ( https://github.com/prettier/prettier )
- [x] Add base responsive breakpoints (@codyhart)
- [x] Rename project with generic name (ex: static-web-starter-kit)

R&D
- [ ] Switch to Preact - https://preactjs.com/guide/switching-to-preact (first attempt: weird issue with refs, missing some warnings, non-compatible with some React components (React.Proptypes) but https://github.com/developit/preact/pull/633 + https://github.com/reactjs/prop-types + latest Preact updates... )
- [ ] Improve animations workflow (DOM / SVG)
- [ ] Setup flow https://flow.org/en/docs/frameworks/react/
- [ ] Build generator with starter kit templates (ex: PHP, i18n, etc)

**Comment by lucasjohnson** [comment]
- Base responsive breakpoints handled with either SASS mixins, Flexbox, or something else (IE fallbacks)?
- R&D OOCSS, BEM and SMACSS or others, or maybe begin writing our our version?
- Base components and CSS (buttons, links etc.), and SASS variables (fonts and colors etc.)
- Langaue toggle and i18n
- R&D accessibility (WCAG etc.)
- Deployment documentation and documentation Wiki in general
